#!/usr/bin/bash

# Volume control script with wob integration
# Usage: volume up|down|mute

WOB_SOCK="$XDG_RUNTIME_DIR/wob.sock"

get_volume() {
    pactl get-sink-volume @DEFAULT_SINK@ | head -n1 | awk '{print $5}' | tr -d '%'
}

get_mute() {
    pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}'
}

send_to_wob() {
    local vol="$1"
    if [[ -p "$WOB_SOCK" ]]; then
        echo "$vol" > "$WOB_SOCK"
    fi
}

case "$1" in
    up)
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        send_to_wob "$(get_volume)"
        ;;
    down)
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        send_to_wob "$(get_volume)"
        ;;
    mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        if [[ "$(get_mute)" == "yes" ]]; then
            send_to_wob 0
        else
            send_to_wob "$(get_volume)"
        fi
        ;;
    *)
        echo "Usage: $0 {up|down|mute}"
        exit 1
        ;;
esac
